spring:
  application:
    name: 'user-service'
  messages:
    basename: i18n/messages
    encoding: utf-8
  security:
    oauth2:
      authorizationserver:
        issuer: ${APPLICATION_USER_SERVICE_URL}
      resourceserver:
        jwt:
          issuer-uri: ${APPLICATION_USER_SERVICE_URL}
      client:
        registration:
          # This ID is used in your Java RestClient code
          internal-user-client:
            provider: myself
            client-id: ${APPLICATION_INTERNAL_CLIENT_ID}
            client-secret: ${APPLICATION_INTERNAL_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          myself:
            token-uri: ${APPLICATION_USER_SERVICE_URL}/oauth2/token
            authorization-uri: ${APPLICATION_USER_SERVICE_URL}/oauth2/authorize
  data:
    mongodb:
      database: userservice
      host: localhost
      port: 27017
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  port: 9000

logging:
  level:
    root: info

application:
  encrypt:
    salt: ${APPLICATION_ENCRYPT_SALT}
    key: ${APPLICATION_ENCRYPT_KEY}
  httpclient:
    maxConnTotal: ${APPLICATION_HTTPCLIENT_MAX_CONN_TOTAL:100}
    maxConnPerRoute: ${APPLICATION_HTTPCLIENT_MAX_CONN_PER_ROUTE:20}
    connectionTimeToLive: ${APPLICATION_HTTPCLIENT_CONNECTION_TIME_TO_LIVE:20}
  mail:
    apiKey: ${APPLICATION_MAIL_API_KEY}
    apiUrl: ${APPLICATION_MAIL_API_URL}
    fromAddress: ${APPLICATION_MAIL_FROM_ADDRESS}
    fromName: ${APPLICATION_MAIL_FROM_NAME}
    testMode: ${APPLICATION_MAIL_TEST_MODE:false}
  memberService:
    apiUrl: ${APPLICATION_MEMBERSERVICE_URL:http://localhost:8080}
  baseUrl: ${APPLICATION_BASE_URL}
  sendActivationRemindersDelay: 3600000
  name: Member Portal User Service
  internal:
    clientId: ${APPLICATION_INTERNAL_CLIENT_ID}
    clientSecret: ${APPLICATION_INTERNAL_CLIENT_SECRET}
    assertionServiceClientId: ${APPLICATION_INTERNAL_ASSERTION_SERVICE_ID}
    assertionServiceClientSecret: ${APPLICATION_INTERNAL_ASSERTION_SERVICE_CLIENT_SECRET}
