#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  logging:
    logstash: # forward logs to ELK
      enabled: false
  metrics:
    logs: # report metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds

spring:
  zipkin:
    enabled: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces to Zipkin
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
  eureka:
    enabled: true
