spring:
  application:
    name: member-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  data:
    mongodb:
      database: memberservice
      host: localhost
      port: 27017
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
server:
  port: 9010
logging:
  level:
    root: info

application:
  encrypt:
    salt: 5a8b9f1d2c6e7a403b5d8e9c0f4a1b32
    key: member-service
  httpclient:
    maxConnTotal: 100
    maxConnPerRoute: 20
    connectionTimeToLive: 5
  mail:
    apiKey: some-key
    apiUrl: http://mail.com/api
    fromAddress: mp@orcid.org
    fromName: member-portal
    testMode: true
    contactUpdateRecipient: someone@orcid.org
  salesforce:
    orcidApiClientId: some-client-id
    orcidApiClientSecret: some-secret
    clientEndpoint: http://some.com/endpoint
    tokenEndpoint: http://some.come/token/endpoint
  userService:
    apiUrl: http://user.com/service
  reports:
    holisticsMemberDashboardUrl: http://holistics.com/member
    holisticsMemberDashboardSecret: some-secret
    holisticsIntegrationDashboardUrl: http://holistics.com/integration
    holisticsIntegrationDashboardSecret: some-secret
    holisticsConsortiaDashboardUrl: http://holistics.com/consortia
    holisticsConsortiaDashboardSecret: some-secret
    holisticsAffiliationDashboardUrl: http://holistics.com/affiliation
    holisticsAffiliationDashboardSecret: some-secret
    holisticsConsortiaMemberAffiliationsDashboardUrl: http://holistics.com/consortiaMember
    holisticsConsortiaMemberAffiliationsDashboardSecret: some-secret